# Generated by Django 5.0.2 on 2024-03-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumnno_profesores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Alumnos',
        ),
        migrations.DeleteModel(
            name='alumnno',
        ),
    ]
